/// Dimension table containing demographic and profile information for each customer, including their race, alignment, home region, and loyalty tier.
table Customer
	lineageTag: 6f0b068c-df37-4952-a01a-e737b979c1f3

	/// Unique integer identifier for each customer. Primary key of the Customer table.
	column 'Customer Key'
		dataType: int64
		isHidden
		isKey
		formatString: 0
		isAvailableInMdx: false
		lineageTag: 7f16a8e9-33c7-4f13-830d-9ab97aea6093
		summarizeBy: none
		sourceColumn: Customer Key

		annotation SummarizationSetBy = Automatic

	/// Full name of the customer.
	column 'Customer Name'
		dataType: string
		lineageTag: 47223014-4d00-46b4-a374-5de2d4944ca9
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	/// The race or species of the customer (e.g. Human, Elf, Beast Man).
	column Race
		dataType: string
		lineageTag: e3059e3c-0fac-4be0-90a1-7fc9ccd8084a
		summarizeBy: none
		sourceColumn: Race

		annotation SummarizationSetBy = Automatic

	/// The moral or faction alignment of the customer (e.g. Heroic, Evil, Neutral).
	column Alignment
		dataType: string
		lineageTag: 25f0008c-9349-47b1-b9d3-59d05a894ed5
		summarizeBy: none
		sourceColumn: Alignment

		annotation SummarizationSetBy = Automatic

	/// The region of Eternia that the customer originates from.
	column 'Home Region'
		dataType: string
		lineageTag: 0d990185-14ef-4fa7-a1da-746dbdf9e2ac
		summarizeBy: none
		sourceColumn: Home Region

		annotation SummarizationSetBy = Automatic

	/// Customer loyalty classification tier, used to segment customers by purchasing behaviour and reward level.
	column 'Loyalty Tier'
		dataType: string
		lineageTag: 817e2da2-4163-45be-a5d6-a59f52a370c1
		summarizeBy: none
		sourceColumn: Loyalty Tier

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/GreyskullAnalytics/eternia-trading-co/refs/heads/main/data/dim_customer.csv"),[Delimiter=",", Columns=6, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_key", Int64.Type}, {"customer_name", type text}, {"race", type text}, {"alignment", type text}, {"home_region", type text}, {"loyalty_tier", type text}}),
				    #"Rename columns" = fn_FormatColumnNames ( #"Changed Type" )
				in
				    #"Rename columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

